[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[build.environment]
  VITE_API_URL = "https://qlib-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200